app_auth/urls.py
from unicodedata import name
from django.urls import path
from .views import *

urlpatterns=[
    path('login',login_toDoc,name='login'),
    path('register',register,name='register'),
    path('logout',logout_f,name='logout'),

    # admin
# 123456


]

blog/urls.py
from django.urls import path
from . import views
urlpatterns=[
path("",views.home,name="home")

]

my_blog/urls.py
from os import stat
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import home,detail,search,document_detail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name="home"),
    path('document/<int:id_document>',detail,name="detail"),
    path('document_detail/<int:id_document>',document_detail,name="document_detail"),
    path('document/recherche',search,name="search"),
    path('auth/',include('app_auth.urls')),
    path('my-admin/',include('app_admin.urls')),
    

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app_auth/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur",widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="Mot de passe",widget=forms.PasswordInput(attrs={'class':'form-control'}))

class RegisterForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur",widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="Mot de passe",widget=forms.PasswordInput(attrs={'class':'form-control'}))
    pwd_confirm = forms.CharField(label="Mot de passe de confirmation",widget=forms.PasswordInput(attrs={'class':'form-control'}))

app_auth/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import *


def login_toDoc(request):  

            # admin
            # 123456                        
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = authenticate(username=username,password=pwd)
            if user is not None:
                login(request,user)
                return redirect('dashboard')
            else:
                messages.error(request,"Authentification échouée")
                return render(request,'login.html',{'form':form})    
        else :
            for field in form.errors:
             form[field].field.widget.attrs['class']+= ' is-invalid'
            return render(request,'login.html',{'form':form})


    else:
        form=LoginForm()

    return render(request,"login.html",{'form':form})


                # admin
                # 123456


def register(request):
    if request.method == "POST":
        form=RegisterForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data["username"]
            pwd=form.cleaned_data["pwd"]
            user = User.objects.create_user(username=username,password=pwd)
            if user is not None:
                return redirect("login")
            else:
                messages.error(request,"création de compte échouée") 
                return render(request,'register.html',{'form':form})   
        else:
            return render(request,'register.html',{'form':form})
            return render(request,"register.html",{})
    else:
  
        
        form = RegisterForm()
        return render(request,"register.html",{'form':form}) 




def logout_f(request):
        logout(request)
        return redirect('login')

app_auth/templates/login.html
{% extends 'base.html' %}


{% block title%}
Connexion

{% endblock %}

{% block content %}

<div class="container">
    
    <div class="col-md-12 mt-5">
        <h1 class="text-center">Connexion</h1>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger text-center">
            <strong>{{message}}</strong>
        </div>
        {% endfor %}
        {% endif %}

        <form method="POST" action="" novalidate>
            {% csrf_token %}

            <div class="card">
                <div class="card-header text-center">
                    connexion
                </div>

                <div class="card-body">
                    <label for="id_utilisateur">Nom utilisateur</label>

                    {% if form.username.errors %}
                    {% for error in form.username.errors%}
                    <div class="div-error-{{form.username.name}}"><small class="text-danger">{{error}}</small></div>
                    {% endfor %}
                    {% endif %}

                    {{form.username}}

                    <label for="id_pwd">mot de passe</label>
                    {% if form.pwd.errors %}
                    {% for error in form.pwd.errors%}
                    <div class="div-error-{{form.pwd.name}}"><small class="text-danger">{{error}}</small></div>
                    {% endfor %}
                    {% endif %}
                    {{form.pwd}}
                </div>

                <div class="card-footer">
                    <button class="btn btn-primary submit" >connecter</button>
                    <p class="text-center">vous n'avez pas de compte ? <a href="{% url 'register' %}">register</a></p>
                </div>

                
            </div>

        </form>


    </div>



</div>
{% endblock %}

app_auth/templates/register.html
{% extends 'base.html' %}


{% block title%}
création de compte

{% endblock %}

{% block content %}

<div class="container">
    <h1 class="text-center">Inscription</h1>
    <div class="col-md-12 mt-5">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger text-center">
            <strong>{{message}}</strong>
        </div>
        {% endfor %}
        {% endif %}

        <form method="POST" action="" novalidate>
            {% csrf_token %}

            <div class="card">
                <div class="card-header text-center">création de compte</div>
                   
                

                <div class="card-body">
                   

                    {{form}}
                </div>

                <div class="card-footer">
                    <button class="btn btn-primary btn-block submit">créer le compte</button>
                    
                </div>
            </div>

        </form>


    </div>



</div>
{% endblock %}